In [2]:
from unityagents import UnityEnvironment
import torch
from torch import nn
from src.model.ddpg import DDPGAgent
from src.model.ppo import PPOAgent

In [3]:
env = UnityEnvironment(file_name='unity/Reacher20.app', no_graphics=False)

INFO:unityagents:
'Academy' started successfully!
Unity Academy name: Academy
        Number of Brains: 1
        Number of External Brains : 1
        Lesson number : 0
        Reset Parameters :
		goal_speed -> 1.0
		goal_size -> 5.0
Unity brain name: ReacherBrain
        Number of Visual Observations (per agent): 0
        Vector Observation space type: continuous
        Vector Observation space size (per agent): 33
        Number of stacked Vector Observation: 1
        Vector Action space type: continuous
        Vector Action space size (per agent): 4
        Vector Action descriptions: , , , 


In [4]:
agent = PPOAgent.from_file(env, 'assets/ppo/PPO.pth')
agent.run_test_episode(track_progress=True)

Mean Cumulative Reward: 39.40: 100%|██████████| 1000/1000 [00:39<00:00, 25.09it/s]


array([39.55999912, 39.53999912, 39.48999912, 39.45999912, 38.78999913,
       39.51999912, 39.41999912, 39.00999913, 39.53999912, 39.36999912,
       39.51999912, 39.41999912, 39.42999912, 39.54999912, 39.01999913,
       39.19999912, 39.46999912, 39.47999912, 39.62999911, 39.56999912])

In [4]:
agent = DDPGAgent.from_file(env, 'assets/ddpg/DDPG.pth')
agent.run_test_episode(track_progress=True)


Mean Cumulative Reward: 38.68: 100%|██████████| 1000/1000 [00:40<00:00, 24.85it/s]


array([[39.47999912, 39.35999912, 39.57999912, 36.87999918, 36.75999918,
        39.49999912, 39.57999912, 39.40999912, 35.8599992 , 39.11999913,
        36.83999918, 39.56999912, 35.9499992 , 39.54999912, 39.54999912,
        38.48999914, 39.52999912, 39.55999912, 39.52999912, 39.57999912]])

In [7]:
agent = DDPGAgent.from_file(env, 'assets/ddpg/DDPG.pth')
agent.run_test_episode(track_progress=True)

Mean Cumulative Reward: 38.83: 100%|██████████| 1000/1000 [00:40<00:00, 24.86it/s]


array([[37.65999916, 38.91999913, 38.06999915, 39.47999912, 39.50999912,
        39.53999912, 39.53999912, 39.53999912, 39.53999912, 39.48999912,
        38.16999915, 39.19999912, 37.41999916, 37.52999916, 39.48999912,
        39.08999913, 39.53999912, 39.51999912, 39.12999913, 36.18999919]])

In [ ]:
# agent = PPOAgent(env, 
#                  network_config={
#                      'actor_hidden_sizes': [256, 128],
#                      'critic_hidden_sizes': [256, 128],
#                      'hidden_activation': nn.ReLU,
#                      'output_activation': nn.Tanh}, seed=4)
# agent.policy.set_state(torch.load('assets/ppo/PPO.pth'))
# agent.run_test_episode(track_progress=True)
# agent = DDPGAgent(env,
#                   network_config={
#                       'actor_hidden_sizes':[256, 128], 
#                       'critic_hidden_sizes':[256, 128]},
#                       seed=4)
# agent.policy.load_state_dict(state_dict=torch.load('assets/ddpg/priority_DDPG.pth'))
# agent.run_test_episode(track_progress=True)